/**
 * PDF generator — Treasure AI 2026 branded report.
 *
 * Brand from "2026 Treasure AI Official Template":
 *   - Header: deep navy #1E1B4B with purple accent #7C3AED
 *   - Body: clean white, black titles, purple section accents
 *   - Light backgrounds: #FAF5FF (soft purple tint)
 *   - Font: Helvetica (jsPDF built-in)
 */

import jsPDF from 'jspdf';
import type { OutputData } from '../stores/experienceLabStore';

// ── Official Treasure AI 2026 palette (RGB) ──
const C = {
  deepBlue:  [45, 64, 170]   as [number, number, number],  // #2D40AA
  purple:    [132, 123, 242]  as [number, number, number],  // #847BF2
  orchid:    [196, 102, 212]  as [number, number, number],  // #C466D4
  skyBlue:   [128, 179, 250]  as [number, number, number],  // #80B3FA
  pinkLight: [243, 204, 242]  as [number, number, number],  // #F3CCF2
  peachLight:[255, 226, 189]  as [number, number, number],  // #FFE2BD
  peach:     [253, 184, 147]  as [number, number, number],  // #FDB893
  nearWhite: [249, 254, 255]  as [number, number, number],  // #F9FEFF
  black:     [0, 0, 0]        as [number, number, number],
  gray800:   [31, 41, 55]     as [number, number, number],
  gray600:   [75, 85, 99]     as [number, number, number],
  gray400:   [156, 163, 175]  as [number, number, number],
  gray200:   [229, 231, 235]  as [number, number, number],
  white:     [255, 255, 255]  as [number, number, number],
};

const PW = 210;  // A4 width mm
const M = 18;    // margin
const CW = PW - 2 * M;

// ── Helpers ──

function checkPage(doc: jsPDF, y: number, needed: number): number {
  if (y + needed > 278) { doc.addPage(); return 22; }
  return y;
}

function sectionTitle(doc: jsPDF, y: number, title: string): number {
  y = checkPage(doc, y, 14);
  doc.setFontSize(10);
  doc.setFont('helvetica', 'bold');
  doc.setTextColor(...C.purple);
  doc.text(title.toUpperCase(), M, y);
  y += 1.5;
  doc.setDrawColor(...C.purple);
  doc.setLineWidth(0.4);
  doc.line(M, y, M + CW, y);
  return y + 5;
}

function bodyText(doc: jsPDF, y: number, text: string, indent = 0): number {
  doc.setFontSize(8.5);
  doc.setFont('helvetica', 'normal');
  doc.setTextColor(...C.gray600);
  const lines = doc.splitTextToSize(text, CW - indent);
  for (const line of lines) {
    y = checkPage(doc, y, 4.5);
    doc.text(line, M + indent, y);
    y += 3.8;
  }
  return y + 1.5;
}

function addFooters(doc: jsPDF) {
  const pageCount = doc.getNumberOfPages();
  for (let p = 1; p <= pageCount; p++) {
    doc.setPage(p);
    // Footer line
    doc.setDrawColor(...C.gray200);
    doc.setLineWidth(0.2);
    doc.line(M, 285, M + CW, 285);
    // Footer text
    doc.setFontSize(6.5);
    doc.setFont('helvetica', 'normal');
    doc.setTextColor(...C.gray400);
    doc.text('Generated by Treasure AI Experience Center  |  treasuredata.com', M, 289);
    doc.text(`${p} / ${pageCount}`, PW - M, 289, { align: 'right' });
  }
}

function drawHeader(doc: jsPDF) {
  // Soft gradient-like header (peach → pink → blue, using layered rects)
  doc.setFillColor(...C.peachLight);
  doc.rect(0, 0, PW, 30, 'F');
  doc.setFillColor(...C.pinkLight);
  doc.rect(PW * 0.3, 0, PW * 0.4, 30, 'F');
  doc.setFillColor(212, 228, 255); // light blue
  doc.rect(PW * 0.6, 0, PW * 0.4, 30, 'F');
  // Accent strip
  doc.setFillColor(...C.purple);
  doc.rect(0, 30, PW * 0.33, 1.2, 'F');
  doc.setFillColor(...C.orchid);
  doc.rect(PW * 0.33, 30, PW * 0.34, 1.2, 'F');
  doc.setFillColor(...C.skyBlue);
  doc.rect(PW * 0.67, 30, PW * 0.33, 1.2, 'F');
  // Branding
  doc.setFontSize(14);
  doc.setFont('helvetica', 'bold');
  doc.setTextColor(...C.deepBlue);
  doc.text('Treasure AI', M, 13);
  doc.setFontSize(16);
  doc.setTextColor(...C.black);
  doc.text('Experience Center', M + 30, 13);
  doc.setFontSize(9);
  doc.setFont('helvetica', 'normal');
  doc.setTextColor(...C.gray600);
  doc.text('Analysis Report', M, 20);
}

// ── Step renderers (correct field names per step type) ──

type Out = Record<string, unknown>;

function renderStepAnalyze(doc: jsPDF, out: Out, y: number): number {
  // Findings: name, insight, level
  if (Array.isArray(out.findings)) {
    const levelColors: Record<string, [number, number, number]> = { High: C.purple, Medium: C.skyBlue, Low: C.gray400 };
    for (const f of out.findings as Array<{ name: string; insight: string; level: string }>) {
      y = checkPage(doc, y, 12);
      const lc = levelColors[f.level] || C.gray400;
      // Left accent bar
      doc.setFillColor(...lc);
      doc.roundedRect(M, y - 2, 1.5, 9, 0.5, 0.5, 'F');
      // Name + level
      doc.setFontSize(9);
      doc.setFont('helvetica', 'bold');
      doc.setTextColor(...C.black);
      doc.text(f.name || '', M + 4, y);
      doc.setFontSize(7);
      doc.setTextColor(...lc);
      doc.text(`[${f.level}]`, M + 4 + doc.getTextWidth(f.name || '') + 2, y);
      // Insight
      doc.setFontSize(8);
      doc.setFont('helvetica', 'normal');
      doc.setTextColor(...C.gray600);
      const lines = doc.splitTextToSize(f.insight || '', CW - 6);
      doc.text(lines, M + 4, y + 4);
      y += 4 + lines.length * 3.5 + 3;
    }
  }
  // Metrics
  if (Array.isArray(out.metrics)) {
    y = checkPage(doc, y, 16);
    const metrics = out.metrics as Array<{ label: string; value: string }>;
    const count = Math.min(metrics.length, 4);
    // Render as stacked rows instead of side-by-side to avoid overlap
    for (const m of metrics.slice(0, 4)) {
      y = checkPage(doc, y, 8);
      doc.setFillColor(...C.nearWhite);
      doc.roundedRect(M, y - 1, CW, 7, 1, 1, 'F');
      doc.setFontSize(10);
      doc.setFont('helvetica', 'bold');
      doc.setTextColor(...C.deepBlue);
      doc.text(m.value || '', M + 3, y + 2.5);
      doc.setFontSize(7);
      doc.setFont('helvetica', 'normal');
      doc.setTextColor(...C.gray600);
      doc.text(m.label || '', M + 50, y + 2.5);
      y += 8;
    }
    y += 2;
  }
  // Rationale
  if (typeof out.rationale === 'string') {
    doc.setFontSize(7.5);
    doc.setFont('helvetica', 'italic');
    doc.setTextColor(...C.gray400);
    y = checkPage(doc, y, 8);
    const lines = doc.splitTextToSize(out.rationale, CW);
    doc.text(lines, M, y);
    y += lines.length * 3.2 + 2;
  }
  return y;
}

function renderStepInspect(doc: jsPDF, out: Out, y: number): number {
  // Profiles: name, level, behavior, action
  if (Array.isArray(out.profiles)) {
    const levelColors: Record<string, [number, number, number]> = { High: C.purple, Medium: C.skyBlue, Low: C.gray400 };
    for (const p of out.profiles as Array<{ name: string; level: string; behavior: string; action: string }>) {
      // Calculate dynamic height
      doc.setFontSize(8);
      doc.setFont('helvetica', 'normal');
      const behaviorLines = doc.splitTextToSize(p.behavior || '', CW - 8);
      const actionLines = doc.splitTextToSize(`Action: ${p.action || ''}`, CW - 8);
      const boxH = 6 + behaviorLines.length * 3.5 + actionLines.length * 3.5 + 2;
      y = checkPage(doc, y, boxH + 4);
      const lc = levelColors[p.level] || C.gray400;
      doc.setFillColor(...C.nearWhite);
      doc.roundedRect(M, y - 2, CW, boxH, 1.5, 1.5, 'F');
      // Name + level
      doc.setFontSize(9);
      doc.setFont('helvetica', 'bold');
      doc.setTextColor(...C.black);
      doc.text(p.name || '', M + 3, y + 1);
      doc.setFontSize(7);
      doc.setTextColor(...lc);
      doc.text(`[${p.level}]`, M + 3 + doc.getTextWidth(p.name || '') + 2, y + 1);
      // Behavior (wrapped)
      doc.setFontSize(8);
      doc.setFont('helvetica', 'normal');
      doc.setTextColor(...C.gray600);
      doc.text(behaviorLines, M + 3, y + 5);
      // Action (wrapped)
      doc.setTextColor(...C.purple);
      doc.text(actionLines, M + 3, y + 5 + behaviorLines.length * 3.5 + 1);
      y += boxH + 3;
    }
  }
  // Sections
  y = renderSections(doc, out, y);
  return y;
}

function renderStepCreate(doc: jsPDF, out: Out, y: number): number {
  // Sections
  y = renderSections(doc, out, y);
  // Channels: name, role
  if (Array.isArray(out.channels)) {
    y = checkPage(doc, y, 8);
    doc.setFontSize(8);
    doc.setFont('helvetica', 'bold');
    doc.setTextColor(...C.gray400);
    doc.text('CHANNELS', M, y);
    y += 4;
    for (const ch of out.channels as Array<{ name: string; role: string }>) {
      y = checkPage(doc, y, 6);
      doc.setFillColor(...C.nearWhite);
      doc.roundedRect(M, y - 2, CW, 6, 1, 1, 'F');
      doc.setFontSize(8.5);
      doc.setFont('helvetica', 'bold');
      doc.setTextColor(...C.black);
      doc.text(ch.name || '', M + 2, y + 1);
      doc.setFont('helvetica', 'normal');
      doc.setTextColor(...C.gray600);
      doc.text(ch.role || '', M + 30, y + 1);
      y += 7;
    }
  }
  // Next steps: action, priority
  if (Array.isArray(out.nextSteps)) {
    y = renderActions(doc, out.nextSteps as Array<{ action: string; priority: string }>, y);
  }
  return y;
}

function renderStepCompare(doc: jsPDF, out: Out, y: number): number {
  if (Array.isArray(out.options)) {
    for (const opt of out.options as Array<{ name: string; description: string; score: string; recommended: boolean }>) {
      // Calculate dynamic height
      doc.setFontSize(8);
      doc.setFont('helvetica', 'normal');
      const descLines = doc.splitTextToSize(opt.description || '', CW - 10);
      const boxH = 8 + descLines.length * 3.5 + 4;
      y = checkPage(doc, y, boxH + 3);
      const borderColor = opt.recommended ? C.purple : C.gray200;
      doc.setDrawColor(...borderColor);
      doc.setLineWidth(opt.recommended ? 0.6 : 0.3);
      doc.roundedRect(M, y - 2, CW, boxH, 1.5, 1.5, 'S');
      // Name + recommended badge
      doc.setFontSize(10);
      doc.setFont('helvetica', 'bold');
      doc.setTextColor(...C.black);
      doc.text(opt.name || '', M + 3, y + 1);
      if (opt.recommended) {
        doc.setFontSize(6);
        doc.setTextColor(...C.purple);
        doc.text('RECOMMENDED', M + CW - 20, y + 1);
      }
      // Score on same line as name
      doc.setFontSize(10);
      doc.setFont('helvetica', 'bold');
      doc.setTextColor(...C.purple);
      doc.text(opt.score || '', M + CW - 5, y + 1, { align: 'right' });
      // Description (wrapped)
      doc.setFontSize(8);
      doc.setFont('helvetica', 'normal');
      doc.setTextColor(...C.gray600);
      doc.text(descLines, M + 3, y + 6);
      y += boxH + 3;
    }
  }
  // Metrics
  if (Array.isArray(out.metrics)) {
    y = renderStepAnalyze(doc, { metrics: out.metrics }, y);
  }
  return y;
}

function renderStepActivate(doc: jsPDF, out: Out, y: number): number {
  if (typeof out.summary === 'string') {
    y = bodyText(doc, y, out.summary);
  }
  // Destinations: channel, role, detail
  if (Array.isArray(out.destinations)) {
    for (const d of out.destinations as Array<{ channel: string; role: string; detail: string }>) {
      doc.setFontSize(8);
      doc.setFont('helvetica', 'normal');
      const detailLines = doc.splitTextToSize(d.detail || '', CW - 8);
      const boxH = 6 + detailLines.length * 3.5 + 1;
      y = checkPage(doc, y, boxH + 3);
      doc.setFillColor(...C.nearWhite);
      doc.roundedRect(M, y - 2, CW, boxH, 1.5, 1.5, 'F');
      doc.setFontSize(9);
      doc.setFont('helvetica', 'bold');
      doc.setTextColor(...C.black);
      doc.text(d.channel || '', M + 3, y + 1);
      doc.setFontSize(7.5);
      doc.setTextColor(...C.purple);
      doc.text(d.role || '', M + 35, y + 1);
      doc.setFontSize(8);
      doc.setFont('helvetica', 'normal');
      doc.setTextColor(...C.gray600);
      doc.text(detailLines, M + 3, y + 5);
      y += boxH + 3;
    }
  }
  y = renderSections(doc, out, y);
  return y;
}

function renderStepOptimize(doc: jsPDF, out: Out, y: number): number {
  if (typeof out.rationale === 'string') {
    doc.setFontSize(8);
    doc.setFont('helvetica', 'italic');
    doc.setTextColor(...C.gray600);
    y = checkPage(doc, y, 8);
    const lines = doc.splitTextToSize(out.rationale, CW);
    doc.text(lines, M, y);
    y += lines.length * 3.5 + 3;
  }
  // Changes: action, priority
  if (Array.isArray(out.changes)) {
    y = renderActions(doc, out.changes as Array<{ action: string; priority: string }>, y);
  }
  // Metrics
  if (Array.isArray(out.metrics)) {
    y = renderStepAnalyze(doc, { metrics: out.metrics }, y);
  }
  return y;
}

// Shared sub-renderers

function renderSections(doc: jsPDF, out: Out, y: number): number {
  if (!Array.isArray(out.sections)) return y;
  for (const sec of out.sections as Array<{ label: string; content: string }>) {
    y = checkPage(doc, y, 10);
    doc.setFontSize(8.5);
    doc.setFont('helvetica', 'bold');
    doc.setTextColor(...C.purple);
    doc.text(sec.label || '', M, y);
    y += 4;
    y = bodyText(doc, y, sec.content || '');
  }
  return y;
}

function renderActions(doc: jsPDF, actions: Array<{ action: string; priority: string }>, y: number): number {
  const priorityColors: Record<string, [number, number, number]> = { 'Do now': C.purple, 'Test next': C.skyBlue, 'Scale later': C.gray400 };
  y = checkPage(doc, y, 6);
  for (const [i, a] of actions.entries()) {
    y = checkPage(doc, y, 6);
    const pc = priorityColors[a.priority] || C.gray400;
    // Number circle
    doc.setFillColor(...C.purple);
    doc.circle(M + 2, y, 2, 'F');
    doc.setFontSize(7);
    doc.setFont('helvetica', 'bold');
    doc.setTextColor(...C.white);
    doc.text(`${i + 1}`, M + 2, y + 0.8, { align: 'center' });
    // Action text
    doc.setFontSize(8.5);
    doc.setFont('helvetica', 'normal');
    doc.setTextColor(...C.gray600);
    doc.text(a.action || '', M + 6, y + 0.5);
    // Priority
    doc.setFontSize(7);
    doc.setFont('helvetica', 'bold');
    doc.setTextColor(...pc);
    doc.text(a.priority || '', M + CW - 2, y + 0.5, { align: 'right' });
    y += 6;
  }
  return y + 2;
}

// ── Step type router ──
const stepRenderers: Record<string, (doc: jsPDF, out: Out, y: number) => number> = {
  analyze: renderStepAnalyze,
  inspect: renderStepInspect,
  create: renderStepCreate,
  compare: renderStepCompare,
  activate: renderStepActivate,
  optimize: renderStepOptimize,
};

// ── Main exports ──

export type WfStep = { stepDef: { label: string; stepType: string }; output: Record<string, unknown> | null; summary: string };

export async function generatePdf(
  output: OutputData | null,
  wfStepHistory?: WfStep[],
): Promise<Blob> {
  const doc = new jsPDF({ orientation: 'portrait', unit: 'mm', format: 'a4' });

  drawHeader(doc);
  let y = 38;

  if (output) {
    y = renderOutputData(doc, output, y);
  } else if (wfStepHistory && wfStepHistory.length > 0) {
    y = renderWorkflowSteps(doc, wfStepHistory, y);
  }

  addFooters(doc);
  return doc.output('blob');
}

function renderWorkflowSteps(doc: jsPDF, steps: WfStep[], startY: number): number {
  let y = startY;

  for (const [i, step] of steps.entries()) {
    y = checkPage(doc, y, 22);

    // Step header card
    doc.setFillColor(...C.nearWhite);
    doc.roundedRect(M, y - 3, CW, 12, 2, 2, 'F');
    // Step number
    doc.setFillColor(...C.purple);
    doc.circle(M + 5, y + 2, 3.5, 'F');
    doc.setFontSize(10);
    doc.setFont('helvetica', 'bold');
    doc.setTextColor(...C.white);
    doc.text(`${i + 1}`, M + 5, y + 3, { align: 'center' });
    // Label
    doc.setFontSize(11);
    doc.setFont('helvetica', 'bold');
    doc.setTextColor(...C.black);
    doc.text(step.stepDef.label, M + 11, y + 1.5);
    // Type badge
    doc.setFontSize(6.5);
    doc.setFont('helvetica', 'bold');
    doc.setTextColor(...C.purple);
    doc.text(step.stepDef.stepType.toUpperCase(), M + 11, y + 6);

    y += 13;

    // Headline
    if (step.output && typeof step.output.headline === 'string') {
      doc.setFontSize(10);
      doc.setFont('helvetica', 'bold');
      doc.setTextColor(...C.deepBlue);
      const hLines = doc.splitTextToSize(step.output.headline, CW);
      doc.text(hLines, M, y);
      y += hLines.length * 4.5 + 2;
    }

    // Impact statement
    if (step.output && typeof step.output.impactStatement === 'string') {
      y = checkPage(doc, y, 7);
      doc.setFillColor(...C.pinkLight);
      doc.roundedRect(M, y - 2, CW, 6, 1, 1, 'F');
      doc.setFontSize(8);
      doc.setFont('helvetica', 'normal');
      doc.setTextColor(...C.purple);
      doc.text(step.output.impactStatement as string, M + 2, y + 1.5);
      y += 8;
    }

    // Step-type-specific rendering
    if (step.output) {
      const renderer = stepRenderers[step.stepDef.stepType];
      if (renderer) {
        y = renderer(doc, step.output, y);
      } else {
        // Generic: just render summary
        if (step.summary) y = bodyText(doc, y, step.summary);
      }
    } else if (step.summary) {
      y = bodyText(doc, y, step.summary);
    }

    // Step separator
    if (i < steps.length - 1) {
      y += 2;
      y = checkPage(doc, y, 4);
      doc.setDrawColor(...C.gray200);
      doc.setLineWidth(0.2);
      doc.line(M + 10, y, M + CW - 10, y);
      y += 6;
    }
  }

  return y;
}

function renderOutputData(doc: jsPDF, output: OutputData, startY: number): number {
  let y = startY;

  // Summary banner
  doc.setFillColor(...C.nearWhite);
  doc.roundedRect(M, y, CW, 24, 2, 2, 'F');
  doc.setFillColor(...C.purple);
  doc.roundedRect(M, y, 1.5, 24, 0.5, 0.5, 'F');
  doc.setFontSize(10);
  doc.setFont('helvetica', 'bold');
  doc.setTextColor(...C.deepBlue);
  const recLines = doc.splitTextToSize(output.summaryBanner.topRecommendation, CW - 8);
  doc.text(recLines, M + 4, y + 6);
  const rh = recLines.length * 4.5;
  doc.setFontSize(7.5);
  doc.setFont('helvetica', 'normal');
  doc.setTextColor(...C.gray600);
  doc.text(`Goal: ${output.summaryBanner.goal}  |  Audience: ${output.summaryBanner.audience}`, M + 4, y + rh + 9);
  doc.setTextColor(...C.purple);
  doc.text(output.summaryBanner.impactFraming, M + 4, y + rh + 13);
  y += 30;

  // Executive Summary
  y = sectionTitle(doc, y, 'Executive Summary');
  y = bodyText(doc, y, output.executiveSummary);

  // Audience Segments
  y = sectionTitle(doc, y, 'Audience Segments');
  const levelColors: Record<string, [number, number, number]> = { High: C.purple, Medium: C.skyBlue, Low: C.gray400 };
  for (const seg of output.audienceCards) {
    y = checkPage(doc, y, 14);
    const lc = levelColors[seg.opportunityLevel] || C.gray400;
    doc.setFillColor(...lc);
    doc.roundedRect(M, y - 2, 1.5, 10, 0.5, 0.5, 'F');
    doc.setFontSize(9);
    doc.setFont('helvetica', 'bold');
    doc.setTextColor(...C.black);
    doc.text(seg.name, M + 4, y);
    doc.setFontSize(7);
    doc.setTextColor(...lc);
    doc.text(`[${seg.opportunityLevel}]`, M + 4 + doc.getTextWidth(seg.name) + 2, y);
    doc.setFontSize(8);
    doc.setFont('helvetica', 'normal');
    doc.setTextColor(...C.gray600);
    doc.text(seg.whyItMatters, M + 4, y + 4);
    doc.setTextColor(...C.purple);
    doc.text(`Action: ${seg.suggestedAction}`, M + 4, y + 8);
    y += 14;
  }

  // Channel Strategy
  y = sectionTitle(doc, y, 'Channel Strategy');
  for (const ch of output.channelStrategy) {
    y = checkPage(doc, y, 6);
    doc.setFillColor(...C.nearWhite);
    doc.roundedRect(M, y - 2, CW, 6, 1, 1, 'F');
    doc.setFontSize(8.5);
    doc.setFont('helvetica', 'bold');
    doc.setTextColor(...C.black);
    doc.text(ch.channel, M + 2, y + 1);
    doc.setFont('helvetica', 'normal');
    doc.setTextColor(...C.gray600);
    doc.text(`${ch.role}  —  ${ch.messageAngle}`, M + 28, y + 1);
    y += 7;
  }
  y += 2;

  // Scenario Core
  y = sectionTitle(doc, y, output.scenarioCore.title);
  for (const sec of output.scenarioCore.sections) {
    y = checkPage(doc, y, 10);
    doc.setFontSize(8.5);
    doc.setFont('helvetica', 'bold');
    doc.setTextColor(...C.purple);
    doc.text(sec.label, M, y);
    y += 4;
    y = bodyText(doc, y, sec.content);
  }

  // KPI Framework
  y = sectionTitle(doc, y, 'KPI Framework');
  const accents = [C.purple, C.skyBlue, C.orchid, C.peach];
  for (const [i, kpi] of output.kpiFramework.entries()) {
    y = checkPage(doc, y, 8);
    const ac = accents[i % accents.length];
    doc.setFillColor(...C.nearWhite);
    doc.roundedRect(M, y - 2, CW, 7, 1, 1, 'F');
    doc.setFillColor(...ac);
    doc.roundedRect(M, y - 2, 1.2, 7, 0.5, 0.5, 'F');
    doc.setFontSize(7);
    doc.setFont('helvetica', 'bold');
    doc.setTextColor(...ac);
    doc.text(kpi.type, M + 3, y);
    doc.setFontSize(8.5);
    doc.setTextColor(...C.deepBlue);
    doc.text(kpi.name, M + 28, y);
    doc.setFontSize(7.5);
    doc.setFont('helvetica', 'normal');
    doc.setTextColor(...C.gray600);
    doc.text(kpi.note, M + 3, y + 4);
    y += 9;
  }

  // Next Actions
  y = sectionTitle(doc, y, 'Recommended Next Actions');
  y = renderActions(doc, output.nextActions.map(a => ({ action: a.action, priority: a.priority })), y);

  return y;
}
