/**
 * Type definitions for the campaign launch hierarchy.
 *
 * A full Meta campaign push includes:
 *   Campaign → Ad Sets → Ad Creatives → Ads
 */

// ── Facebook Page ────────────────────────────────────────────────────────────

export interface FacebookPage {
  id: string;
  name: string;
  access_token?: string;
}

// ── Creative File (image / video uploaded for ad creative) ────────────────────

export interface CreativeFile {
  fileName: string;
  filePath: string;
  fileSize: number;
  mimeType: string;
  /** Data-URI preview generated by the file-selector IPC handler */
  previewUrl: string;
  /** Hash returned by Meta after upload */
  imageHash?: string;
}

// ── Campaign ─────────────────────────────────────────────────────────────────

export interface LaunchCampaignConfig {
  name: string;
  objective: string;
  dailyBudget: number; // cents
  status: 'PAUSED' | 'ACTIVE';
  specialAdCategories: string[];
  buyingType: string;
  startDate?: string;
  endDate?: string;
}

// ── Ad Set ───────────────────────────────────────────────────────────────────

export interface LaunchAdSetConfig {
  localId: string;
  name: string;
  dailyBudget: number; // cents
  optimizationGoal: string;
  billingEvent: string;
  targeting: {
    geoLocations?: { countries: string[] };
    ageMin?: number;
    ageMax?: number;
  };
  status: 'PAUSED' | 'ACTIVE';
  /** Label describing the audience this ad set targets */
  audienceLabel: string;
  /** TD CDP segment ID for audience activation */
  tdSegmentId?: string;
}

// ── Ad Creative ──────────────────────────────────────────────────────────────

export interface LaunchAdCreativeConfig {
  localId: string;
  name: string;
  headline: string;
  bodyText: string;
  ctaType: string;
  linkUrl: string;
  file?: CreativeFile;
  pageId: string;
}

// ── Ad ───────────────────────────────────────────────────────────────────────

export interface LaunchAdConfig {
  localId: string;
  name: string;
  /** References LaunchAdSetConfig.localId */
  adSetLocalId: string;
  /** References LaunchAdCreativeConfig.localId */
  creativeLocalId: string;
  status: 'PAUSED' | 'ACTIVE';
}

// ── Full config ──────────────────────────────────────────────────────────────

export interface CampaignLaunchConfig {
  campaign: LaunchCampaignConfig;
  adSets: LaunchAdSetConfig[];
  creatives: LaunchAdCreativeConfig[];
  ads: LaunchAdConfig[];
  facebookPages: FacebookPage[];
}

// ── Launch progress tracking ─────────────────────────────────────────────────

export type LaunchStepName =
  | 'createCampaign'
  | 'createAdSets'
  | 'uploadImages'
  | 'createAdCreatives'
  | 'createAds'
  | 'activateAudience';

export interface LaunchStepResult {
  step: LaunchStepName;
  label: string;
  status: 'pending' | 'in_progress' | 'success' | 'error' | 'skipped';
  error?: string;
  /** IDs created by this step */
  createdIds?: string[];
}

export interface LaunchProgress {
  overallStatus: 'idle' | 'launching' | 'success' | 'partial_success' | 'error';
  currentStep: LaunchStepName | null;
  stepResults: LaunchStepResult[];
  /** Platform campaign ID once created */
  campaignId?: string;
  /** Maps local ad set IDs → platform IDs */
  adSetIdMap: Record<string, string>;
  /** Maps local creative IDs → platform IDs */
  creativeIdMap: Record<string, string>;
  /** Maps local ad IDs → platform IDs */
  adIdMap: Record<string, string>;
}

// ── Saved launch config (persisted to localStorage) ─────────────────────────

export interface SavedLaunchConfig {
  id: string;
  name: string;
  createdAt: string;
  updatedAt: string;
  config: CampaignLaunchConfig;
  sourceBlueprintId?: string;
  sourceBlueprintName?: string;
  platformCampaignId?: string;
  isEditMode: boolean;
  /** Program this config belongs to (if created within a program workflow) */
  programId?: string;
  /** Channel platform this config targets within a program */
  channelPlatform?: 'meta' | 'google' | 'tiktok' | 'snapchat' | 'pinterest';
}
